### ISSUE TITLE
Test don't re-run in watch mode.

### ISSUE THREAD

**Issue by pavloko** [typescriptcrew/ts-react-slingshot#12]
When I run `npm run test:watch`, I assume that test would re-run on every file change; however, it does not happen, the test just hangs there. I'm using clean install without any modifications. I wonder if anybody else had this issue. Thanks.

P.S. Thanks the author for the great starting point.

**Comment by nickytonline** [comment]
@pavloko, I'll need to see what's up. I have the same behavior.

**Comment by nickytonline** [comment]
@pavloko, the project I forked this from, https://github.com/coryhouse/react-slingshot, uses Jest now. When I fix/implement #21, this should be a non-issue.
