### ISSUE TITLE
Upgrade to TypeScript 2.0

### ISSUE THREAD

**Issue by nickytonline** [typescriptcrew/ts-react-slingshot#15]
Upgrade to TypeScript 2.0 and upgrade webpack loader. For TS.

**Comment by ASlightMelody** [comment]
Could the repo also pull all changes from react-slingshot? The packages are quite out of date (e.g. react 0.14.7 in ts-react-slingshot vs. 15.3.1 in react-slingshot). Thanks for your efforts.

**Comment by nickytonline** [comment]
@ASlightMelody, when I forked it originally it was just to test if I could integrate TS. A lot changed in the react-slingshot project, so when I have more free time, I can probably tackle this. Probably in the next couple of weeks.

**Comment by nickytonline** [comment]
@ASlightMelody, I haven't had a chance to look at this yet. Honestly, I think it will probably be a while before I can tackle this.

Here's what I see need being done:
* Update the source and add new typings if required.
* See what to do about code coverage. isparta and TypeScript don't work together. remap-instanbul could be an option I believe. Having said that, [react-slingshot is looking to move towards Jest potentially](https://github.com/coryhouse/react-slingshot/issues/262) which allows you to plug TypeScript and since Jest has code coverage, this could be another solution.
* ts-node which is used to write the unit tests in TypeScript, doesn't seem to work with TS 2.0 (from what I've seen initially)

I think that this is pretty much it... ;)

**Comment by nickytonline** [comment]
Closing as this is going to happen in #21.
