### ISSUE TITLE
Missing Sourcemaps

### ISSUE THREAD

**Issue by Mattes83** [typescriptcrew/ts-react-slingshot#20]
When I run 'npm run start' I dont get any sourcemaps in chrome.

**Comment by nickytonline** [comment]
@Mattes83, with a clean install I have no problem seeing the source maps. Please see the attached screenshot.
![screenshot from 2016-11-06 01-58-41](https://cloud.githubusercontent.com/assets/833231/20035692/6b3b6704-a3bc-11e6-98f3-dbf1b6baca26.png)
