### ISSUE TITLE
Issue in react-slingshot adding typescript support

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [typescriptcrew/ts-react-slingshot#24]
When I add a configureStore.ts like in the sample application in react-slingshot, I get error on:
const composeEnhancers = window.REDUX_DEVTOOLS_EXTENSION_COMPOSE || compose; // add support for Redux dev tools

The error says:
ERROR in [at-loader] src\store\configureStore.ts:33:35
TS2339: Property 'REDUX_DEVTOOLS_EXTENSION_COMPOSE' does not exist on type 'Window'.

Thanks.

**Comment by nickytonline** [comment]
You need to type the window to an interface that extends Window. I.e.
Sorry. On my phone, so I'll explain with an example.
```
interface ReduxDevToolsWindow extends Window
{
REDUX_DEVTOOLS_EXTENSION_COMPOSE: // type the function here.
}
```

And then use it like this
```
const composeEnhancers = (window as ReduxDevToolsWindow).REDUX_DEVTOOLS_EXTENSION_COMPOSE || compose
```

If you're still stuck, feel free to reopen and comment.
