### ISSUE TITLE
Plans to update the repository to webpack 2.* and typescript 2.*?

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [typescriptcrew/ts-react-slingshot#25]
I did update to add typescript support based on the ts-react-starter repo, however would love to see react-slingshot updated. Thanks.

**Comment by nickytonline** [comment]
@Rajiv-Kulkarni, I'll be doing this soon, but if you want it right away, configurations are available in the latest release of [ts-react-starter](https://github.com/nickytonline/ts-react-starter/releases/tag/1.1.0).

**Comment by nickytonline** [comment]
Also, there already is aTS 2.x, #15

**Comment by Rajiv-Kulkarni** [comment]
Thanks.

**Comment by nickytonline** [comment]
Closing as #21 will include this.
